crowdanki_uuid: b23f90cc-8c5b-11ea-b50b-9cb6d098820d
deck_config_uuid: b23f90cd-8c5b-11ea-b50b-9cb6d098820d
deck_configurations:
- __type__: DeckConfig
  autoplay: true
  crowdanki_uuid: b23f90cd-8c5b-11ea-b50b-9cb6d098820d
  dyn: false
  lapse:
    delays:
    - 10
    leechAction: 0
    leechFails: 8
    minInt: 1
    mult: 0.0
  maxTaken: 60
  name: Default
  new:
    LBEIMinAfter: 4
    LBEIMinBefore: 4
    LBGIMinAfter: 1
    LBGIMinBefore: 1
    bury: false
    delays:
    - 1
    - 10
    initialFactor: 2500
    ints:
    - 1
    - 4
    - 7
    order: 1
    perDay: 20
    separate: true
  replayq: true
  rev:
    bury: false
    ease4: 1.3
    fuzz: 0.05
    hardFactor: 1.2
    ivlFct: 1.0
    maxIvl: 36500
    minSpace: 1
    perDay: 200
  timer: 0
desc: <b>This is my deck.</b> There are many like it, but this one is mine.
dyn: 0
extendNew: 10
extendRev: 50
name: General
